export const PLAY = "PLAY";
export const SET_TOKEN = "SET_TOKEN";
export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
export const SEARCH_ALBUMS_FULFILLED = "SEARCH_ALBUMS_FULFILLED";
export const SEARCH_ALBUMS_REJECTED = "SEARCH_ALBUMS_REJECTED";
export const GET_ALBUM_INFO = "GET_ALBUM_INFO";
export const GET_ALBUM_INFO_FULFILLED = "GET_ALBUM_INFO_FULFILLED"; 